#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[System.Data.Linq.Mapping.DatabaseAttribute(Name="LarsBotten")]
public partial class LarsBottenDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertUsersTBL(UsersTBL instance);
  partial void UpdateUsersTBL(UsersTBL instance);
  partial void DeleteUsersTBL(UsersTBL instance);
  partial void InsertCellsTBL(CellsTBL instance);
  partial void UpdateCellsTBL(CellsTBL instance);
  partial void DeleteCellsTBL(CellsTBL instance);
  partial void InsertCellNotesTBL(CellNotesTBL instance);
  partial void UpdateCellNotesTBL(CellNotesTBL instance);
  partial void DeleteCellNotesTBL(CellNotesTBL instance);
  partial void InsertContactsTBL(ContactsTBL instance);
  partial void UpdateContactsTBL(ContactsTBL instance);
  partial void DeleteContactsTBL(ContactsTBL instance);
  partial void InsertImagesTBL(ImagesTBL instance);
  partial void UpdateImagesTBL(ImagesTBL instance);
  partial void DeleteImagesTBL(ImagesTBL instance);
  partial void InsertImageNotesTBL(ImageNotesTBL instance);
  partial void UpdateImageNotesTBL(ImageNotesTBL instance);
  partial void DeleteImageNotesTBL(ImageNotesTBL instance);
  #endregion
	
	public LarsBottenDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["LarsBottenConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public LarsBottenDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public LarsBottenDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public LarsBottenDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public LarsBottenDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<UsersTBL> UsersTBLs
	{
		get
		{
			return this.GetTable<UsersTBL>();
		}
	}
	
	public System.Data.Linq.Table<CellsTBL> CellsTBLs
	{
		get
		{
			return this.GetTable<CellsTBL>();
		}
	}
	
	public System.Data.Linq.Table<CellNotesTBL> CellNotesTBLs
	{
		get
		{
			return this.GetTable<CellNotesTBL>();
		}
	}
	
	public System.Data.Linq.Table<ContactsTBL> ContactsTBLs
	{
		get
		{
			return this.GetTable<ContactsTBL>();
		}
	}
	
	public System.Data.Linq.Table<ImagesTBL> ImagesTBLs
	{
		get
		{
			return this.GetTable<ImagesTBL>();
		}
	}
	
	public System.Data.Linq.Table<ImageNotesTBL> ImageNotesTBLs
	{
		get
		{
			return this.GetTable<ImageNotesTBL>();
		}
	}
}

[Table(Name="dbo.[User]")]
public partial class UsersTBL : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _user_id;
	
	private string _username;
	
	private string _password;
	
	private string _accesslevel;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onuser_idChanging(int value);
    partial void Onuser_idChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnaccesslevelChanging(string value);
    partial void OnaccesslevelChanged();
    #endregion
	
	public UsersTBL()
	{
		OnCreated();
	}
	
	[Column(Storage="_user_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int user_id
	{
		get
		{
			return this._user_id;
		}
		set
		{
			if ((this._user_id != value))
			{
				this.Onuser_idChanging(value);
				this.SendPropertyChanging();
				this._user_id = value;
				this.SendPropertyChanged("user_id");
				this.Onuser_idChanged();
			}
		}
	}
	
	[Column(Storage="_username", DbType="NVarChar(50)")]
	public string username
	{
		get
		{
			return this._username;
		}
		set
		{
			if ((this._username != value))
			{
				this.OnusernameChanging(value);
				this.SendPropertyChanging();
				this._username = value;
				this.SendPropertyChanged("username");
				this.OnusernameChanged();
			}
		}
	}
	
	[Column(Storage="_password", DbType="NVarChar(50)")]
	public string password
	{
		get
		{
			return this._password;
		}
		set
		{
			if ((this._password != value))
			{
				this.OnpasswordChanging(value);
				this.SendPropertyChanging();
				this._password = value;
				this.SendPropertyChanged("password");
				this.OnpasswordChanged();
			}
		}
	}
	
	[Column(Storage="_accesslevel", DbType="NVarChar(50)")]
	public string accesslevel
	{
		get
		{
			return this._accesslevel;
		}
		set
		{
			if ((this._accesslevel != value))
			{
				this.OnaccesslevelChanging(value);
				this.SendPropertyChanging();
				this._accesslevel = value;
				this.SendPropertyChanged("accesslevel");
				this.OnaccesslevelChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[Table(Name="dbo.Cell")]
public partial class CellsTBL : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _cell_id;
	
	private System.Nullable<int> _parent_id;
	
	private string _name;
	
	private string _ingress;
	
	private string _description;
	
	private System.Nullable<int> _priority;
	
	private string _active;
	
	private string _credit_1_t;
	
	private string _credit_1;
	
	private string _credit_2_t;
	
	private string _credit_2;
	
	private string _credit_3_t;
	
	private string _credit_3;
	
	private string _credit_4_t;
	
	private string _credit_4;
	
	private string _credit_5_t;
	
	private string _credit_5;
	
	private string _credit_6_t;
	
	private string _credit_6;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncell_idChanging(int value);
    partial void Oncell_idChanged();
    partial void Onparent_idChanging(System.Nullable<int> value);
    partial void Onparent_idChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OningressChanging(string value);
    partial void OningressChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OnpriorityChanging(System.Nullable<int> value);
    partial void OnpriorityChanged();
    partial void OnactiveChanging(string value);
    partial void OnactiveChanged();
    partial void Oncredit_1_tChanging(string value);
    partial void Oncredit_1_tChanged();
    partial void Oncredit_1Changing(string value);
    partial void Oncredit_1Changed();
    partial void Oncredit_2_tChanging(string value);
    partial void Oncredit_2_tChanged();
    partial void Oncredit_2Changing(string value);
    partial void Oncredit_2Changed();
    partial void Oncredit_3_tChanging(string value);
    partial void Oncredit_3_tChanged();
    partial void Oncredit_3Changing(string value);
    partial void Oncredit_3Changed();
    partial void Oncredit_4_tChanging(string value);
    partial void Oncredit_4_tChanged();
    partial void Oncredit_4Changing(string value);
    partial void Oncredit_4Changed();
    partial void Oncredit_5_tChanging(string value);
    partial void Oncredit_5_tChanged();
    partial void Oncredit_5Changing(string value);
    partial void Oncredit_5Changed();
    partial void Oncredit_6_tChanging(string value);
    partial void Oncredit_6_tChanged();
    partial void Oncredit_6Changing(string value);
    partial void Oncredit_6Changed();
    #endregion
	
	public CellsTBL()
	{
		OnCreated();
	}
	
	[Column(Storage="_cell_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int cell_id
	{
		get
		{
			return this._cell_id;
		}
		set
		{
			if ((this._cell_id != value))
			{
				this.Oncell_idChanging(value);
				this.SendPropertyChanging();
				this._cell_id = value;
				this.SendPropertyChanged("cell_id");
				this.Oncell_idChanged();
			}
		}
	}
	
	[Column(Storage="_parent_id", DbType="Int")]
	public System.Nullable<int> parent_id
	{
		get
		{
			return this._parent_id;
		}
		set
		{
			if ((this._parent_id != value))
			{
				this.Onparent_idChanging(value);
				this.SendPropertyChanging();
				this._parent_id = value;
				this.SendPropertyChanged("parent_id");
				this.Onparent_idChanged();
			}
		}
	}
	
	[Column(Storage="_name", DbType="NVarChar(50)")]
	public string name
	{
		get
		{
			return this._name;
		}
		set
		{
			if ((this._name != value))
			{
				this.OnnameChanging(value);
				this.SendPropertyChanging();
				this._name = value;
				this.SendPropertyChanged("name");
				this.OnnameChanged();
			}
		}
	}
	
	[Column(Storage="_ingress", DbType="NVarChar(200)")]
	public string ingress
	{
		get
		{
			return this._ingress;
		}
		set
		{
			if ((this._ingress != value))
			{
				this.OningressChanging(value);
				this.SendPropertyChanging();
				this._ingress = value;
				this.SendPropertyChanged("ingress");
				this.OningressChanged();
			}
		}
	}
	
	[Column(Storage="_description", DbType="NVarChar(200)")]
	public string description
	{
		get
		{
			return this._description;
		}
		set
		{
			if ((this._description != value))
			{
				this.OndescriptionChanging(value);
				this.SendPropertyChanging();
				this._description = value;
				this.SendPropertyChanged("description");
				this.OndescriptionChanged();
			}
		}
	}
	
	[Column(Storage="_priority", DbType="Int")]
	public System.Nullable<int> priority
	{
		get
		{
			return this._priority;
		}
		set
		{
			if ((this._priority != value))
			{
				this.OnpriorityChanging(value);
				this.SendPropertyChanging();
				this._priority = value;
				this.SendPropertyChanged("priority");
				this.OnpriorityChanged();
			}
		}
	}
	
	[Column(Storage="_active", DbType="NVarChar(50)")]
	public string active
	{
		get
		{
			return this._active;
		}
		set
		{
			if ((this._active != value))
			{
				this.OnactiveChanging(value);
				this.SendPropertyChanging();
				this._active = value;
				this.SendPropertyChanged("active");
				this.OnactiveChanged();
			}
		}
	}
	
	[Column(Storage="_credit_1_t", DbType="NVarChar(50)")]
	public string credit_1_t
	{
		get
		{
			return this._credit_1_t;
		}
		set
		{
			if ((this._credit_1_t != value))
			{
				this.Oncredit_1_tChanging(value);
				this.SendPropertyChanging();
				this._credit_1_t = value;
				this.SendPropertyChanged("credit_1_t");
				this.Oncredit_1_tChanged();
			}
		}
	}
	
	[Column(Storage="_credit_1", DbType="NVarChar(50)")]
	public string credit_1
	{
		get
		{
			return this._credit_1;
		}
		set
		{
			if ((this._credit_1 != value))
			{
				this.Oncredit_1Changing(value);
				this.SendPropertyChanging();
				this._credit_1 = value;
				this.SendPropertyChanged("credit_1");
				this.Oncredit_1Changed();
			}
		}
	}
	
	[Column(Storage="_credit_2_t", DbType="NVarChar(50)")]
	public string credit_2_t
	{
		get
		{
			return this._credit_2_t;
		}
		set
		{
			if ((this._credit_2_t != value))
			{
				this.Oncredit_2_tChanging(value);
				this.SendPropertyChanging();
				this._credit_2_t = value;
				this.SendPropertyChanged("credit_2_t");
				this.Oncredit_2_tChanged();
			}
		}
	}
	
	[Column(Storage="_credit_2", DbType="NVarChar(50)")]
	public string credit_2
	{
		get
		{
			return this._credit_2;
		}
		set
		{
			if ((this._credit_2 != value))
			{
				this.Oncredit_2Changing(value);
				this.SendPropertyChanging();
				this._credit_2 = value;
				this.SendPropertyChanged("credit_2");
				this.Oncredit_2Changed();
			}
		}
	}
	
	[Column(Storage="_credit_3_t", DbType="NVarChar(50)")]
	public string credit_3_t
	{
		get
		{
			return this._credit_3_t;
		}
		set
		{
			if ((this._credit_3_t != value))
			{
				this.Oncredit_3_tChanging(value);
				this.SendPropertyChanging();
				this._credit_3_t = value;
				this.SendPropertyChanged("credit_3_t");
				this.Oncredit_3_tChanged();
			}
		}
	}
	
	[Column(Storage="_credit_3", DbType="NVarChar(50)")]
	public string credit_3
	{
		get
		{
			return this._credit_3;
		}
		set
		{
			if ((this._credit_3 != value))
			{
				this.Oncredit_3Changing(value);
				this.SendPropertyChanging();
				this._credit_3 = value;
				this.SendPropertyChanged("credit_3");
				this.Oncredit_3Changed();
			}
		}
	}
	
	[Column(Storage="_credit_4_t", DbType="NVarChar(50)")]
	public string credit_4_t
	{
		get
		{
			return this._credit_4_t;
		}
		set
		{
			if ((this._credit_4_t != value))
			{
				this.Oncredit_4_tChanging(value);
				this.SendPropertyChanging();
				this._credit_4_t = value;
				this.SendPropertyChanged("credit_4_t");
				this.Oncredit_4_tChanged();
			}
		}
	}
	
	[Column(Storage="_credit_4", DbType="NVarChar(50)")]
	public string credit_4
	{
		get
		{
			return this._credit_4;
		}
		set
		{
			if ((this._credit_4 != value))
			{
				this.Oncredit_4Changing(value);
				this.SendPropertyChanging();
				this._credit_4 = value;
				this.SendPropertyChanged("credit_4");
				this.Oncredit_4Changed();
			}
		}
	}
	
	[Column(Storage="_credit_5_t", DbType="NVarChar(50)")]
	public string credit_5_t
	{
		get
		{
			return this._credit_5_t;
		}
		set
		{
			if ((this._credit_5_t != value))
			{
				this.Oncredit_5_tChanging(value);
				this.SendPropertyChanging();
				this._credit_5_t = value;
				this.SendPropertyChanged("credit_5_t");
				this.Oncredit_5_tChanged();
			}
		}
	}
	
	[Column(Storage="_credit_5", DbType="NVarChar(50)")]
	public string credit_5
	{
		get
		{
			return this._credit_5;
		}
		set
		{
			if ((this._credit_5 != value))
			{
				this.Oncredit_5Changing(value);
				this.SendPropertyChanging();
				this._credit_5 = value;
				this.SendPropertyChanged("credit_5");
				this.Oncredit_5Changed();
			}
		}
	}
	
	[Column(Storage="_credit_6_t", DbType="NVarChar(50)")]
	public string credit_6_t
	{
		get
		{
			return this._credit_6_t;
		}
		set
		{
			if ((this._credit_6_t != value))
			{
				this.Oncredit_6_tChanging(value);
				this.SendPropertyChanging();
				this._credit_6_t = value;
				this.SendPropertyChanged("credit_6_t");
				this.Oncredit_6_tChanged();
			}
		}
	}
	
	[Column(Storage="_credit_6", DbType="NVarChar(50)")]
	public string credit_6
	{
		get
		{
			return this._credit_6;
		}
		set
		{
			if ((this._credit_6 != value))
			{
				this.Oncredit_6Changing(value);
				this.SendPropertyChanging();
				this._credit_6 = value;
				this.SendPropertyChanged("credit_6");
				this.Oncredit_6Changed();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[Table(Name="dbo.CellNote")]
public partial class CellNotesTBL : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _cellnote_id;
	
	private System.Nullable<int> _cell_id;
	
	private string _author;
	
	private string _date;
	
	private string _note;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncellnote_idChanging(int value);
    partial void Oncellnote_idChanged();
    partial void Oncell_idChanging(System.Nullable<int> value);
    partial void Oncell_idChanged();
    partial void OnauthorChanging(string value);
    partial void OnauthorChanged();
    partial void OndateChanging(string value);
    partial void OndateChanged();
    partial void OnnoteChanging(string value);
    partial void OnnoteChanged();
    #endregion
	
	public CellNotesTBL()
	{
		OnCreated();
	}
	
	[Column(Storage="_cellnote_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int cellnote_id
	{
		get
		{
			return this._cellnote_id;
		}
		set
		{
			if ((this._cellnote_id != value))
			{
				this.Oncellnote_idChanging(value);
				this.SendPropertyChanging();
				this._cellnote_id = value;
				this.SendPropertyChanged("cellnote_id");
				this.Oncellnote_idChanged();
			}
		}
	}
	
	[Column(Storage="_cell_id", DbType="Int")]
	public System.Nullable<int> cell_id
	{
		get
		{
			return this._cell_id;
		}
		set
		{
			if ((this._cell_id != value))
			{
				this.Oncell_idChanging(value);
				this.SendPropertyChanging();
				this._cell_id = value;
				this.SendPropertyChanged("cell_id");
				this.Oncell_idChanged();
			}
		}
	}
	
	[Column(Storage="_author", DbType="NVarChar(50)")]
	public string author
	{
		get
		{
			return this._author;
		}
		set
		{
			if ((this._author != value))
			{
				this.OnauthorChanging(value);
				this.SendPropertyChanging();
				this._author = value;
				this.SendPropertyChanged("author");
				this.OnauthorChanged();
			}
		}
	}
	
	[Column(Storage="_date", DbType="NVarChar(50)")]
	public string date
	{
		get
		{
			return this._date;
		}
		set
		{
			if ((this._date != value))
			{
				this.OndateChanging(value);
				this.SendPropertyChanging();
				this._date = value;
				this.SendPropertyChanged("date");
				this.OndateChanged();
			}
		}
	}
	
	[Column(Storage="_note", DbType="NVarChar(50)")]
	public string note
	{
		get
		{
			return this._note;
		}
		set
		{
			if ((this._note != value))
			{
				this.OnnoteChanging(value);
				this.SendPropertyChanging();
				this._note = value;
				this.SendPropertyChanged("note");
				this.OnnoteChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[Table(Name="dbo.Contact")]
public partial class ContactsTBL : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _contact_id;
	
	private string _name;
	
	private string _address;
	
	private string _postnumber;
	
	private string _place;
	
	private string _country;
	
	private string _phone;
	
	private string _fax;
	
	private string _email;
	
	private string _www;
	
	private System.Nullable<int> _priority;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncontact_idChanging(int value);
    partial void Oncontact_idChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void OnpostnumberChanging(string value);
    partial void OnpostnumberChanged();
    partial void OnplaceChanging(string value);
    partial void OnplaceChanged();
    partial void OncountryChanging(string value);
    partial void OncountryChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    partial void OnfaxChanging(string value);
    partial void OnfaxChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnwwwChanging(string value);
    partial void OnwwwChanged();
    partial void OnpriorityChanging(System.Nullable<int> value);
    partial void OnpriorityChanged();
    #endregion
	
	public ContactsTBL()
	{
		OnCreated();
	}
	
	[Column(Storage="_contact_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int contact_id
	{
		get
		{
			return this._contact_id;
		}
		set
		{
			if ((this._contact_id != value))
			{
				this.Oncontact_idChanging(value);
				this.SendPropertyChanging();
				this._contact_id = value;
				this.SendPropertyChanged("contact_id");
				this.Oncontact_idChanged();
			}
		}
	}
	
	[Column(Storage="_name", DbType="NVarChar(50)")]
	public string name
	{
		get
		{
			return this._name;
		}
		set
		{
			if ((this._name != value))
			{
				this.OnnameChanging(value);
				this.SendPropertyChanging();
				this._name = value;
				this.SendPropertyChanged("name");
				this.OnnameChanged();
			}
		}
	}
	
	[Column(Storage="_address", DbType="NVarChar(50)")]
	public string address
	{
		get
		{
			return this._address;
		}
		set
		{
			if ((this._address != value))
			{
				this.OnaddressChanging(value);
				this.SendPropertyChanging();
				this._address = value;
				this.SendPropertyChanged("address");
				this.OnaddressChanged();
			}
		}
	}
	
	[Column(Storage="_postnumber", DbType="NVarChar(50)")]
	public string postnumber
	{
		get
		{
			return this._postnumber;
		}
		set
		{
			if ((this._postnumber != value))
			{
				this.OnpostnumberChanging(value);
				this.SendPropertyChanging();
				this._postnumber = value;
				this.SendPropertyChanged("postnumber");
				this.OnpostnumberChanged();
			}
		}
	}
	
	[Column(Storage="_place", DbType="NVarChar(50)")]
	public string place
	{
		get
		{
			return this._place;
		}
		set
		{
			if ((this._place != value))
			{
				this.OnplaceChanging(value);
				this.SendPropertyChanging();
				this._place = value;
				this.SendPropertyChanged("place");
				this.OnplaceChanged();
			}
		}
	}
	
	[Column(Storage="_country", DbType="NVarChar(50)")]
	public string country
	{
		get
		{
			return this._country;
		}
		set
		{
			if ((this._country != value))
			{
				this.OncountryChanging(value);
				this.SendPropertyChanging();
				this._country = value;
				this.SendPropertyChanged("country");
				this.OncountryChanged();
			}
		}
	}
	
	[Column(Storage="_phone", DbType="NVarChar(50)")]
	public string phone
	{
		get
		{
			return this._phone;
		}
		set
		{
			if ((this._phone != value))
			{
				this.OnphoneChanging(value);
				this.SendPropertyChanging();
				this._phone = value;
				this.SendPropertyChanged("phone");
				this.OnphoneChanged();
			}
		}
	}
	
	[Column(Storage="_fax", DbType="NVarChar(50)")]
	public string fax
	{
		get
		{
			return this._fax;
		}
		set
		{
			if ((this._fax != value))
			{
				this.OnfaxChanging(value);
				this.SendPropertyChanging();
				this._fax = value;
				this.SendPropertyChanged("fax");
				this.OnfaxChanged();
			}
		}
	}
	
	[Column(Storage="_email", DbType="NVarChar(50)")]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this.OnemailChanging(value);
				this.SendPropertyChanging();
				this._email = value;
				this.SendPropertyChanged("email");
				this.OnemailChanged();
			}
		}
	}
	
	[Column(Storage="_www", DbType="NVarChar(50)")]
	public string www
	{
		get
		{
			return this._www;
		}
		set
		{
			if ((this._www != value))
			{
				this.OnwwwChanging(value);
				this.SendPropertyChanging();
				this._www = value;
				this.SendPropertyChanged("www");
				this.OnwwwChanged();
			}
		}
	}
	
	[Column(Storage="_priority", DbType="Int")]
	public System.Nullable<int> priority
	{
		get
		{
			return this._priority;
		}
		set
		{
			if ((this._priority != value))
			{
				this.OnpriorityChanging(value);
				this.SendPropertyChanging();
				this._priority = value;
				this.SendPropertyChanged("priority");
				this.OnpriorityChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[Table(Name="dbo.Image")]
public partial class ImagesTBL : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _image_id;
	
	private System.Nullable<int> _cell_id;
	
	private System.Nullable<int> _promote_id;
	
	private string _name;
	
	private string _ingress;
	
	private string _description;
	
	private string _active;
	
	private System.Nullable<int> _priority;
	
	private System.Nullable<int> _promotepriority;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onimage_idChanging(int value);
    partial void Onimage_idChanged();
    partial void Oncell_idChanging(System.Nullable<int> value);
    partial void Oncell_idChanged();
    partial void Onpromote_idChanging(System.Nullable<int> value);
    partial void Onpromote_idChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OningressChanging(string value);
    partial void OningressChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OnactiveChanging(string value);
    partial void OnactiveChanged();
    partial void OnpriorityChanging(System.Nullable<int> value);
    partial void OnpriorityChanged();
    partial void OnpromotepriorityChanging(System.Nullable<int> value);
    partial void OnpromotepriorityChanged();
    #endregion
	
	public ImagesTBL()
	{
		OnCreated();
	}
	
	[Column(Storage="_image_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int image_id
	{
		get
		{
			return this._image_id;
		}
		set
		{
			if ((this._image_id != value))
			{
				this.Onimage_idChanging(value);
				this.SendPropertyChanging();
				this._image_id = value;
				this.SendPropertyChanged("image_id");
				this.Onimage_idChanged();
			}
		}
	}
	
	[Column(Storage="_cell_id", DbType="Int")]
	public System.Nullable<int> cell_id
	{
		get
		{
			return this._cell_id;
		}
		set
		{
			if ((this._cell_id != value))
			{
				this.Oncell_idChanging(value);
				this.SendPropertyChanging();
				this._cell_id = value;
				this.SendPropertyChanged("cell_id");
				this.Oncell_idChanged();
			}
		}
	}
	
	[Column(Storage="_promote_id", DbType="Int")]
	public System.Nullable<int> promote_id
	{
		get
		{
			return this._promote_id;
		}
		set
		{
			if ((this._promote_id != value))
			{
				this.Onpromote_idChanging(value);
				this.SendPropertyChanging();
				this._promote_id = value;
				this.SendPropertyChanged("promote_id");
				this.Onpromote_idChanged();
			}
		}
	}
	
	[Column(Storage="_name", DbType="NVarChar(50)")]
	public string name
	{
		get
		{
			return this._name;
		}
		set
		{
			if ((this._name != value))
			{
				this.OnnameChanging(value);
				this.SendPropertyChanging();
				this._name = value;
				this.SendPropertyChanged("name");
				this.OnnameChanged();
			}
		}
	}
	
	[Column(Storage="_ingress", DbType="NVarChar(200)")]
	public string ingress
	{
		get
		{
			return this._ingress;
		}
		set
		{
			if ((this._ingress != value))
			{
				this.OningressChanging(value);
				this.SendPropertyChanging();
				this._ingress = value;
				this.SendPropertyChanged("ingress");
				this.OningressChanged();
			}
		}
	}
	
	[Column(Storage="_description", DbType="NVarChar(200)")]
	public string description
	{
		get
		{
			return this._description;
		}
		set
		{
			if ((this._description != value))
			{
				this.OndescriptionChanging(value);
				this.SendPropertyChanging();
				this._description = value;
				this.SendPropertyChanged("description");
				this.OndescriptionChanged();
			}
		}
	}
	
	[Column(Storage="_active", DbType="NVarChar(50)")]
	public string active
	{
		get
		{
			return this._active;
		}
		set
		{
			if ((this._active != value))
			{
				this.OnactiveChanging(value);
				this.SendPropertyChanging();
				this._active = value;
				this.SendPropertyChanged("active");
				this.OnactiveChanged();
			}
		}
	}
	
	[Column(Storage="_priority", DbType="Int")]
	public System.Nullable<int> priority
	{
		get
		{
			return this._priority;
		}
		set
		{
			if ((this._priority != value))
			{
				this.OnpriorityChanging(value);
				this.SendPropertyChanging();
				this._priority = value;
				this.SendPropertyChanged("priority");
				this.OnpriorityChanged();
			}
		}
	}
	
	[Column(Storage="_promotepriority", DbType="Int")]
	public System.Nullable<int> promotepriority
	{
		get
		{
			return this._promotepriority;
		}
		set
		{
			if ((this._promotepriority != value))
			{
				this.OnpromotepriorityChanging(value);
				this.SendPropertyChanging();
				this._promotepriority = value;
				this.SendPropertyChanged("promotepriority");
				this.OnpromotepriorityChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[Table(Name="dbo.ImageNote")]
public partial class ImageNotesTBL : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _imagenote_id;
	
	private System.Nullable<int> _image_id;
	
	private string _author;
	
	private string _date;
	
	private string _note;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onimagenote_idChanging(int value);
    partial void Onimagenote_idChanged();
    partial void Onimage_idChanging(System.Nullable<int> value);
    partial void Onimage_idChanged();
    partial void OnauthorChanging(string value);
    partial void OnauthorChanged();
    partial void OndateChanging(string value);
    partial void OndateChanged();
    partial void OnnoteChanging(string value);
    partial void OnnoteChanged();
    #endregion
	
	public ImageNotesTBL()
	{
		OnCreated();
	}
	
	[Column(Storage="_imagenote_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int imagenote_id
	{
		get
		{
			return this._imagenote_id;
		}
		set
		{
			if ((this._imagenote_id != value))
			{
				this.Onimagenote_idChanging(value);
				this.SendPropertyChanging();
				this._imagenote_id = value;
				this.SendPropertyChanged("imagenote_id");
				this.Onimagenote_idChanged();
			}
		}
	}
	
	[Column(Storage="_image_id", DbType="Int")]
	public System.Nullable<int> image_id
	{
		get
		{
			return this._image_id;
		}
		set
		{
			if ((this._image_id != value))
			{
				this.Onimage_idChanging(value);
				this.SendPropertyChanging();
				this._image_id = value;
				this.SendPropertyChanged("image_id");
				this.Onimage_idChanged();
			}
		}
	}
	
	[Column(Storage="_author", DbType="NVarChar(50)")]
	public string author
	{
		get
		{
			return this._author;
		}
		set
		{
			if ((this._author != value))
			{
				this.OnauthorChanging(value);
				this.SendPropertyChanging();
				this._author = value;
				this.SendPropertyChanged("author");
				this.OnauthorChanged();
			}
		}
	}
	
	[Column(Storage="_date", DbType="NVarChar(50)")]
	public string date
	{
		get
		{
			return this._date;
		}
		set
		{
			if ((this._date != value))
			{
				this.OndateChanging(value);
				this.SendPropertyChanging();
				this._date = value;
				this.SendPropertyChanged("date");
				this.OndateChanged();
			}
		}
	}
	
	[Column(Storage="_note", DbType="NVarChar(50)")]
	public string note
	{
		get
		{
			return this._note;
		}
		set
		{
			if ((this._note != value))
			{
				this.OnnoteChanging(value);
				this.SendPropertyChanging();
				this._note = value;
				this.SendPropertyChanged("note");
				this.OnnoteChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
